server:
  port: 80
spring:
  application:
    name: summo-resource
#  profiles:
#    active: prod
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.31.42.42:3306/summo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://192.168.56.100:3306/summo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml


#logging:
#  level:
#    #    root: debug    # 更详细的启动日志
#    #    org.springframework.web: info  #默认
#    com.phoenixhell.summoresource: debug


