server:
  port: 10002
spring:
  application:
    name: security-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

