server:
  port: 10001
#  servlet:
#    context-path: uaa
spring:
  application:
    name: security-uaa
  profiles:
    active: prod
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.100:3306/vueadmin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.100
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 3600000
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
#    root: debug    # 更详细的启动日志
#    org.springframework.web: info  #默认
    com.phoenixhell.securityuaa: debug

security:
  baseUrl: http://uaa.security.com

