server:
  port: 10000
spring:
  application:
    name: security-uaa
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    root: debug
    org.springframework.web: info
